<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'OCA\\Theming\\Capabilities' => $baseDir . '/../lib/Capabilities.php',
    'OCA\\Theming\\Controller\\IconController' => $baseDir . '/../lib/Controller/IconController.php',
    'OCA\\Theming\\Controller\\ThemingController' => $baseDir . '/../lib/Controller/ThemingController.php',
    'OCA\\Theming\\IconBuilder' => $baseDir . '/../lib/IconBuilder.php',
    'OCA\\Theming\\ImageManager' => $baseDir . '/../lib/ImageManager.php',
    'OCA\\Theming\\Settings\\Admin' => $baseDir . '/../lib/Settings/Admin.php',
    'OCA\\Theming\\Settings\\Section' => $baseDir . '/../lib/Settings/Section.php',
    'OCA\\Theming\\ThemingDefaults' => $baseDir . '/../lib/ThemingDefaults.php',
    'OCA\\Theming\\Util' => $baseDir . '/../lib/Util.php',
);
