<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitTheming
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OCA\\Theming\\' => 12,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OCA\\Theming\\' => 
        array (
            0 => __DIR__ . '/..' . '/../lib',
        ),
    );

    public static $classMap = array (
        'OCA\\Theming\\Capabilities' => __DIR__ . '/..' . '/../lib/Capabilities.php',
        'OCA\\Theming\\Controller\\IconController' => __DIR__ . '/..' . '/../lib/Controller/IconController.php',
        'OCA\\Theming\\Controller\\ThemingController' => __DIR__ . '/..' . '/../lib/Controller/ThemingController.php',
        'OCA\\Theming\\IconBuilder' => __DIR__ . '/..' . '/../lib/IconBuilder.php',
        'OCA\\Theming\\ImageManager' => __DIR__ . '/..' . '/../lib/ImageManager.php',
        'OCA\\Theming\\Settings\\Admin' => __DIR__ . '/..' . '/../lib/Settings/Admin.php',
        'OCA\\Theming\\Settings\\Section' => __DIR__ . '/..' . '/../lib/Settings/Section.php',
        'OCA\\Theming\\ThemingDefaults' => __DIR__ . '/..' . '/../lib/ThemingDefaults.php',
        'OCA\\Theming\\Util' => __DIR__ . '/..' . '/../lib/Util.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitTheming::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitTheming::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitTheming::$classMap;

        }, null, ClassLoader::class);
    }
}
